-   id: susscanner
    name: Sustainability Scanner
    description: Validate AWS CloudFormation templates against AWS Well-Architected Sustainability Pillar best practices.
    entry: 'susscanner'
    language: python
